name: Atualizar README com Últimos Repositórios

on:
  schedule:
    - cron: "0 */2 * * *" # A cada 6 horas
  workflow_dispatch: # Manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configura Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instala dependências
        run: npm install axios

      - name: Executa script para atualizar README
        run: node update-readme.js

      - name: Commit e Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git commit -m "Atualiza projetos recentes no README" || echo "Nada para commitar"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
